import { useState, useCallback, useRef } from 'react';
import { Link } from 'react-router-dom';
import { analyzeSituation } from '../services/analysisApi';
import { getTheoryIdForFramework } from '../data/frameworkToTheoryId';
import '../App.css';
import './ApplyPage.css';

const MIN_CHARS = 500;
const MAX_CHARS = 1000;
const SITUATION_TYPES = [
  { value: '', label: 'Select type (optional)' },
  { value: 'workplace', label: 'Workplace' },
  { value: 'relationships', label: 'Relationships' },
  { value: 'personal_habits', label: 'Personal habits' },
  { value: 'family', label: 'Family' },
  { value: 'health', label: 'Health' },
  { value: 'financial', label: 'Financial' },
  { value: 'social', label: 'Social' },
  { value: 'other', label: 'Other' },
];

const JOURNAL_KEY = 'psychology-app-journal';

function loadJournal() {
  try {
    const raw = localStorage.getItem(JOURNAL_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveToJournal(entry) {
  const journal = loadJournal();
  const newEntry = {
    id: crypto.randomUUID?.() ?? `id-${Date.now()}`,
    createdAt: new Date().toISOString(),
    situationType: entry.situationType || '',
    isPrivate: entry.isPrivate ?? true,
    inputPreview: entry.inputPreview || '',
    analysis: entry.analysis,
    // When shared anonymously we could store a stripped version; for now we store as-is and rely on isPrivate
  };
  journal.unshift(newEntry);
  localStorage.setItem(JOURNAL_KEY, JSON.stringify(journal));
  return newEntry.id;
}

function deleteFromJournal(id) {
  const journal = loadJournal().filter((e) => e.id !== id);
  localStorage.setItem(JOURNAL_KEY, JSON.stringify(journal));
}

export function ApplyPage() {
  const [input, setInput] = useState('');
  const [situationType, setSituationType] = useState('');
  const [isPrivate, setIsPrivate] = useState(true);
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [savedId, setSavedId] = useState(null);
  const [journal, setJournal] = useState(() => loadJournal());
  const analysisRef = useRef(null);

  const len = input.length;
  const isValid = len >= MIN_CHARS && len <= MAX_CHARS;
  const overMax = len > MAX_CHARS;

  const handleSubmit = useCallback(
    async (e) => {
      e.preventDefault();
      if (!isValid || loading) return;
      setError(null);
      setAnalysis(null);
      setLoading(true);
      try {
        const result = await analyzeSituation(input);
        setAnalysis(result);
      } catch (err) {
        setError(err.message || 'Analysis failed. Please try again.');
      } finally {
        setLoading(false);
      }
    },
    [input, isValid, loading]
  );

  const handleSaveToJournal = useCallback(() => {
    if (!analysis) return;
    const id = saveToJournal({
      situationType,
      isPrivate,
      inputPreview: input.slice(0, 100),
      analysis,
    });
    setSavedId(id);
    setJournal(loadJournal());
  }, [analysis, situationType, isPrivate, input]);

  const handleViewJournalEntry = useCallback((entry) => {
    setAnalysis(entry.analysis);
    setSavedId(entry.id);
    setError(null);
    analysisRef.current?.scrollIntoView?.({ behavior: 'smooth' });
  }, []);

  const handleDeleteJournalEntry = useCallback((id) => {
    deleteFromJournal(id);
    setJournal(loadJournal());
    if (savedId === id) {
      setSavedId(null);
      setAnalysis(null);
    }
  }, [savedId]);

  const handleExportPdf = useCallback(() => {
    if (!analysisRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Psychological Analysis</title>
          <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Source+Sans+3:wght@400;600;700&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'Source Sans 3', sans-serif; padding: 2rem; max-width: 700px; margin: 0 auto; color: #2c2925; line-height: 1.6; }
            h1, h2, h3 { font-family: 'DM Serif Display', serif; }
            h2 { margin-top: 1.5rem; font-size: 1.25rem; border-bottom: 1px solid #e5e0d8; padding-bottom: 0.25rem; }
            .reframe { background: #f8f6f3; padding: 1rem; border-radius: 8px; margin: 0.5rem 0 1rem; }
            ul { padding-left: 1.25rem; }
            li { margin-bottom: 0.5rem; }
            .framework { margin-bottom: 1rem; padding: 0.75rem; border: 1px solid #e5e0d8; border-radius: 8px; }
            .strategy { margin-bottom: 0.75rem; }
          </style>
        </head>
        <body>
          <h1>Psychological Analysis</h1>
          <p><em>Generated by Apply to Your Life</em></p>
          ${analysisRef.current.innerHTML}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  }, []);

  return (
    <div className="apply-page">
      <header className="apply-page__header">
        <div className="apply-page__header-bg" aria-hidden="true" />
        <div className="apply-page__header-inner">
          <Link to="/" className="apply-page__back">
            ← All ideas
          </Link>
          <h1 className="apply-page__title">Apply to Your Life</h1>
          <p className="apply-page__tagline">
            Describe a real situation and receive a structured psychological analysis—non-judgmental, evidence-based, and focused on understanding.
          </p>
        </div>
      </header>

      <main className="apply-page__main">
        {journal.length > 0 && (
          <section className="apply-page__journal-section" aria-labelledby="journal-heading">
            <h2 id="journal-heading" className="apply-page__section-title">
              Your journal
            </h2>
            <p className="apply-page__journal-hint">Saved analyses. Stored locally on this device.</p>
            <ul className="apply-page__journal-list">
              {journal.map((entry) => (
                <li key={entry.id} className="apply-page__journal-item">
                  <div className="apply-page__journal-item-main">
                    <time dateTime={entry.createdAt} className="apply-page__journal-date">
                      {new Date(entry.createdAt).toLocaleDateString(undefined, {
                        dateStyle: 'medium',
                      })}
                    </time>
                    <p className="apply-page__journal-preview">{entry.inputPreview || 'No preview'}…</p>
                  </div>
                  <div className="apply-page__journal-actions">
                    <button
                      type="button"
                      className="apply-page__btn apply-page__btn--secondary apply-page__btn--small"
                      onClick={() => handleViewJournalEntry(entry)}
                      aria-label={`View analysis from ${entry.createdAt}`}
                    >
                      View
                    </button>
                    <button
                      type="button"
                      className="apply-page__btn apply-page__btn--danger apply-page__btn--small"
                      onClick={() => handleDeleteJournalEntry(entry.id)}
                      aria-label={`Delete entry from ${entry.createdAt}`}
                    >
                      Delete
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          </section>
        )}

        <section
          className="apply-page__form-section"
          aria-labelledby="apply-form-heading"
        >
          <h2 id="apply-form-heading" className="apply-page__section-title">
            Your situation
          </h2>
          <form onSubmit={handleSubmit} className="apply-page__form" noValidate>
            <label htmlFor="apply-input" className="apply-page__label">
              Describe your situation
            </label>
            <textarea
              id="apply-input"
              className="apply-page__textarea"
              rows={8}
              placeholder="Describe a situation you're facing. Be specific about what happened, who was involved, and how you felt..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              disabled={loading}
              minLength={MIN_CHARS}
              maxLength={MAX_CHARS}
              aria-describedby="apply-char-count apply-char-hint"
              aria-invalid={overMax || (len > 0 && len < MIN_CHARS)}
            />
            <div id="apply-char-hint" className="apply-page__hint" aria-live="polite">
              {len < MIN_CHARS && len > 0 && (
                <span className="apply-page__hint--error">
                  Please write at least {MIN_CHARS} characters ({MIN_CHARS - len} more).
                </span>
              )}
              {overMax && (
                <span className="apply-page__hint--error">
                  Please shorten to {MAX_CHARS} characters or fewer.
                </span>
              )}
            </div>
            <div
              id="apply-char-count"
              className={`apply-page__char-count ${overMax ? 'apply-page__char-count--over' : ''}`}
              aria-live="polite"
            >
              {len} / {MAX_CHARS}
            </div>

            <div className="apply-page__options">
              <div className="apply-page__field">
                <label htmlFor="apply-type" className="apply-page__label apply-page__label--inline">
                  Situation type
                </label>
                <select
                  id="apply-type"
                  className="apply-page__select"
                  value={situationType}
                  onChange={(e) => setSituationType(e.target.value)}
                  disabled={loading}
                  aria-label="Situation type (optional)"
                >
                  {SITUATION_TYPES.map((opt) => (
                    <option key={opt.value || 'none'} value={opt.value}>
                      {opt.label}
                    </option>
                  ))}
                </select>
              </div>
              <div className="apply-page__field apply-page__field--toggle">
                <span className="apply-page__label apply-page__label--inline">Privacy</span>
                <button
                  type="button"
                  role="switch"
                  aria-checked={!isPrivate}
                  aria-label={isPrivate ? 'Keep private (currently private)' : 'Share anonymously (currently shared)'}
                  className={`apply-page__toggle ${!isPrivate ? 'apply-page__toggle--on' : ''}`}
                  onClick={() => setIsPrivate((p) => !p)}
                  disabled={loading}
                >
                  <span className="apply-page__toggle-track">
                    <span className="apply-page__toggle-thumb" />
                  </span>
                  <span className="apply-page__toggle-label">
                    {isPrivate ? 'Keep private' : 'Share anonymously'}
                  </span>
                </button>
              </div>
            </div>

            <button
              type="submit"
              className="apply-page__submit"
              disabled={!isValid || loading}
              aria-busy={loading}
            >
              {loading ? 'Analyzing…' : 'Get analysis'}
            </button>
          </form>
        </section>

        {loading && (
          <section className="apply-page__loading" aria-live="polite">
            <div className="apply-page__loading-spinner" aria-hidden="true" />
            <p className="apply-page__loading-text">Analyzing your situation…</p>
            <p className="apply-page__loading-sub">This may take a moment.</p>
          </section>
        )}

        {error && (
          <section className="apply-page__error" role="alert">
            <p>{error}</p>
            <p className="apply-page__error-hint">
              Make sure <code>VITE_OPENAI_API_KEY</code> is set in your <code>.env</code> file.
            </p>
          </section>
        )}

        {analysis && !loading && (
          <section
            className="apply-page__analysis"
            aria-labelledby="analysis-heading"
          >
            <h2 id="analysis-heading" className="apply-page__section-title">
              Your analysis
            </h2>

            <div className="apply-page__analysis-actions">
              <button
                type="button"
                className="apply-page__btn apply-page__btn--secondary"
                onClick={handleSaveToJournal}
                disabled={!!savedId}
              >
                {savedId ? 'Saved to journal' : 'Save to journal'}
              </button>
              <button
                type="button"
                className="apply-page__btn apply-page__btn--secondary"
                onClick={handleExportPdf}
              >
                Export as PDF
              </button>
            </div>

            <div ref={analysisRef} className="apply-page__analysis-content">
            <div className="apply-page__reframe apply-page__block">
              <h3 className="apply-page__block-title">What&apos;s happening here</h3>
              <p className="apply-page__reframe-text">{analysis.reframe}</p>
            </div>

            {analysis.frameworks?.length > 0 && (
              <div className="apply-page__block">
                <h3 className="apply-page__block-title">Relevant psychological frameworks</h3>
                <FrameworkCards frameworks={analysis.frameworks} />
              </div>
            )}

            {analysis.questions?.length > 0 && (
              <div className="apply-page__block">
                <h3 className="apply-page__block-title">Questions to consider</h3>
                <ul className="apply-page__list">
                  {analysis.questions.map((q, i) => (
                    <li key={i}>{q}</li>
                  ))}
                </ul>
              </div>
            )}

            {analysis.strategies?.length > 0 && (
              <div className="apply-page__block">
                <h3 className="apply-page__block-title">Actionable strategies</h3>
                <ol className="apply-page__strategies">
                  {analysis.strategies.map((s, i) => (
                    <li key={i} className="apply-page__strategy">
                      <span className="apply-page__strategy-action">{s.action}</span>
                      {s.principle && (
                        <span className="apply-page__strategy-principle">Principle: {s.principle}</span>
                      )}
                      {s.outcome && (
                        <span className="apply-page__strategy-outcome">Expected: {s.outcome}</span>
                      )}
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {analysis.deeper && (
              <details className="apply-page__deeper apply-page__block">
                <summary className="apply-page__deeper-summary">Deeper exploration</summary>
                <div className="apply-page__deeper-content">
                  {analysis.deeper.alternatives && (
                    <p><strong>Alternative interpretations:</strong> {analysis.deeper.alternatives}</p>
                  )}
                  {analysis.deeper.blindspots && (
                    <p><strong>Potential blind spots:</strong> {analysis.deeper.blindspots}</p>
                  )}
                  {analysis.deeper.patterns && (
                    <p><strong>Broader patterns:</strong> {analysis.deeper.patterns}</p>
                  )}
                </div>
              </details>
            )}
            </div>
          </section>
        )}
      </main>
    </div>
  );
}

function FrameworkCards({ frameworks }) {
  return (
    <ul className="apply-page__framework-list" role="list">
      {frameworks.map((fw, i) => (
        <FrameworkCard key={i} index={i} framework={fw} />
      ))}
    </ul>
  );
}

function FrameworkCard({ index, framework }) {
  const [open, setOpen] = useState(false);
  const theoryId = getTheoryIdForFramework(framework.name);
  const contentId = `framework-${index}-content`;

  return (
    <li className="apply-page__framework-card">
      <button
        type="button"
        className="apply-page__framework-head"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        aria-controls={contentId}
      >
        <span className="apply-page__framework-name">{framework.name}</span>
        <span className="apply-page__framework-toggle" aria-hidden="true">
          {open ? '−' : '+'}
        </span>
      </button>
      <div
        id={contentId}
        className="apply-page__framework-body"
        hidden={!open}
      >
        {framework.explanation && <p>{framework.explanation}</p>}
        {framework.application && (
          <p className="apply-page__framework-application"><strong>Application:</strong> {framework.application}</p>
        )}
        {theoryId && (
          <Link to={`/idea/${theoryId}`} className="apply-page__learn-more">
            Explore this concept further →
          </Link>
        )}
      </div>
    </li>
  );
}

export default ApplyPage;
