import { useState, useCallback, useRef } from 'react';
import { Link } from 'react-router-dom';
import { QUIZ_QUESTIONS, tallyScores, resolveDimensions } from '../data/quizQuestions';
import { buildProfile } from '../data/profileEngine';
import { ProfileCard } from '../components/ProfileCard';
import './WhoAmIPage.css';

const PROFILE_KEY = 'psychology-app-profile';
const TOTAL = QUIZ_QUESTIONS.length;

function loadSavedProfile() {
  try {
    const raw = localStorage.getItem(PROFILE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function saveProfile(profile) {
  localStorage.setItem(PROFILE_KEY, JSON.stringify({
    ...profile,
    savedAt: new Date().toISOString(),
  }));
}

export function WhoAmIPage() {
  const [phase, setPhase] = useState(() => {
    const saved = loadSavedProfile();
    return saved ? 'results' : 'welcome';
  });
  const [currentQ, setCurrentQ] = useState(0);
  const [answers, setAnswers] = useState(Array(TOTAL).fill(null));
  const [profile, setProfile] = useState(() => loadSavedProfile());
  const [animating, setAnimating] = useState(false);
  const resultRef = useRef(null);

  const progress = answers.filter((a) => a !== null).length;
  const question = QUIZ_QUESTIONS[currentQ];

  // ── Quiz Navigation ──

  const handleStart = useCallback(() => {
    setPhase('quiz');
    setCurrentQ(0);
    setAnswers(Array(TOTAL).fill(null));
    setProfile(null);
  }, []);

  const handleAnswer = useCallback((optionIdx) => {
    setAnswers((prev) => {
      const next = [...prev];
      next[currentQ] = optionIdx;
      return next;
    });

    // Auto-advance after short delay
    setAnimating(true);
    setTimeout(() => {
      setAnimating(false);
      if (currentQ < TOTAL - 1) {
        setCurrentQ((q) => q + 1);
      }
    }, 350);
  }, [currentQ]);

  const handlePrev = useCallback(() => {
    if (currentQ > 0) setCurrentQ((q) => q - 1);
  }, [currentQ]);

  const handleNext = useCallback(() => {
    if (currentQ < TOTAL - 1) setCurrentQ((q) => q + 1);
  }, [currentQ]);

  // ── Finish Quiz ──

  const handleFinish = useCallback(() => {
    const tallies = tallyScores(answers);
    const dims = resolveDimensions(tallies);
    const result = buildProfile(dims);
    setProfile(result);
    saveProfile(result);
    setPhase('results');
    setTimeout(() => {
      resultRef.current?.scrollIntoView?.({ behavior: 'smooth' });
    }, 100);
  }, [answers]);

  const handleRetake = useCallback(() => {
    localStorage.removeItem(PROFILE_KEY);
    setProfile(null);
    setPhase('welcome');
  }, []);

  // ── PDF Export ──

  const handleExport = useCallback(() => {
    if (!resultRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>My Psychology Profile</title>
          <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Source+Sans+3:wght@400;600;700&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'Source Sans 3', sans-serif; padding: 2rem; max-width: 700px; margin: 0 auto; color: #2c2925; line-height: 1.6; }
            h1, h2, h3 { font-family: 'DM Serif Display', serif; font-weight: 400; }
            h2 { margin-top: 1.5rem; font-size: 1.25rem; border-bottom: 1px solid #e5e0d8; padding-bottom: 0.25rem; }
            a { color: #5c4d3c; }
            .hero { text-align: center; padding: 1.5rem; background: #f8f6f3; border-radius: 12px; margin-bottom: 1.5rem; }
            .dim { display: flex; justify-content: space-between; padding: 0.4rem 0; border-bottom: 1px solid #eee; }
            .day { margin-bottom: 1rem; padding: 0.75rem; border: 1px solid #e5e0d8; border-radius: 8px; }
            .day-num { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; color: #5c4d3c; }
            .feature { margin-bottom: 0.5rem; }
            @media print { body { padding: 0; } }
          </style>
        </head>
        <body>
          <h1>My Psychology Profile</h1>
          ${resultRef.current.innerHTML}
          <p style="margin-top:2rem;font-size:0.8rem;color:#999;">Generated by Psychology Across the World</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  }, []);

  // ── Dimension section label ──
  function getDimensionLabel(qIndex) {
    const dims = { selfAwareness: 'Self-Awareness', challenge: 'Your Challenge', learningStyle: 'How You Learn', introspection: 'Introspection', goal: 'Your Goal' };
    return dims[QUIZ_QUESTIONS[qIndex]?.dimension] || '';
  }

  // Is this the first question of its dimension group?
  const showDimLabel = currentQ === 0 || QUIZ_QUESTIONS[currentQ].dimension !== QUIZ_QUESTIONS[currentQ - 1]?.dimension;

  const allAnswered = progress === TOTAL;

  return (
    <div className="whoami-page">
      <header className="whoami-page__header">
        <div className="whoami-page__header-bg" aria-hidden="true" />
        <div className="whoami-page__header-inner">
          <Link to="/" className="whoami-page__back">← Home</Link>
          <h1 className="whoami-page__title">Who Am I?</h1>
          <p className="whoami-page__subtitle">
            {phase === 'results'
              ? 'Your personalized psychology profile'
              : 'Discover your psychological profile and get a personalized learning path'}
          </p>
        </div>
      </header>

      <main className="whoami-page__main">
        {/* ════ Welcome Phase ════ */}
        {phase === 'welcome' && (
          <div className="whoami-page__welcome">
            <div className="whoami-page__welcome-card">
              <h2 className="whoami-page__welcome-title">Build Your Psychology Profile</h2>
              <p className="whoami-page__welcome-text">
                Answer 18 scenario-based questions to discover your psychological archetype,
                primary challenges, learning style, and get a personalized curriculum designed just for you.
              </p>
              <div className="whoami-page__welcome-dims">
                <div className="whoami-page__welcome-dim">
                  <span className="whoami-page__welcome-dim-icon">🔍</span>
                  <span>Self-Awareness Level</span>
                </div>
                <div className="whoami-page__welcome-dim">
                  <span className="whoami-page__welcome-dim-icon">🎯</span>
                  <span>Primary Life Challenge</span>
                </div>
                <div className="whoami-page__welcome-dim">
                  <span className="whoami-page__welcome-dim-icon">📚</span>
                  <span>Learning Style</span>
                </div>
                <div className="whoami-page__welcome-dim">
                  <span className="whoami-page__welcome-dim-icon">🧘</span>
                  <span>Introspection Comfort</span>
                </div>
                <div className="whoami-page__welcome-dim">
                  <span className="whoami-page__welcome-dim-icon">🎓</span>
                  <span>Application Goal</span>
                </div>
              </div>
              <p className="whoami-page__welcome-note">
                Takes about 5 minutes. No right or wrong answers — just honest ones.
              </p>
              <button type="button" className="whoami-page__start-btn" onClick={handleStart}>
                Begin Assessment
              </button>
            </div>
          </div>
        )}

        {/* ════ Quiz Phase ════ */}
        {phase === 'quiz' && question && (
          <div className="whoami-page__quiz">
            {/* Progress bar */}
            <div className="whoami-page__progress">
              <div className="whoami-page__progress-bar">
                <div
                  className="whoami-page__progress-fill"
                  style={{ width: `${(progress / TOTAL) * 100}%` }}
                />
              </div>
              <span className="whoami-page__progress-text">{progress} / {TOTAL}</span>
            </div>

            {/* Question */}
            <div className={`whoami-page__question${animating ? ' whoami-page__question--exit' : ''}`}>
              {showDimLabel && (
                <span className="whoami-page__dim-label">{getDimensionLabel(currentQ)}</span>
              )}
              <h2 className="whoami-page__scenario">{question.scenario}</h2>
              <div className="whoami-page__options">
                {question.options.map((opt, i) => (
                  <button
                    key={i}
                    type="button"
                    className={`whoami-page__option${answers[currentQ] === i ? ' whoami-page__option--selected' : ''}`}
                    onClick={() => handleAnswer(i)}
                  >
                    <span className="whoami-page__option-letter">{String.fromCharCode(65 + i)}</span>
                    <span className="whoami-page__option-text">{opt.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Navigation */}
            <div className="whoami-page__nav">
              <button
                type="button"
                className="whoami-page__nav-btn"
                onClick={handlePrev}
                disabled={currentQ === 0}
              >
                ← Previous
              </button>
              <span className="whoami-page__nav-qnum">Q{currentQ + 1} of {TOTAL}</span>
              {currentQ < TOTAL - 1 ? (
                <button
                  type="button"
                  className="whoami-page__nav-btn"
                  onClick={handleNext}
                  disabled={answers[currentQ] === null}
                >
                  Next →
                </button>
              ) : (
                <button
                  type="button"
                  className="whoami-page__nav-btn whoami-page__nav-btn--finish"
                  onClick={handleFinish}
                  disabled={!allAnswered}
                >
                  See My Profile
                </button>
              )}
            </div>
          </div>
        )}

        {/* ════ Results Phase ════ */}
        {phase === 'results' && profile && (
          <div className="whoami-page__results" ref={resultRef}>
            <ProfileCard
              profile={profile}
              onRetake={handleRetake}
              onExport={handleExport}
            />
          </div>
        )}
      </main>
    </div>
  );
}
